In [126]:
import json

In [127]:
def read_data(filename):
    with open(filename,"r") as f:
        data=json.load(f)
        return data

In [135]:
data=read_data("store_data.json")


In [136]:
def clean_data(data):
    letter_to_rating={"one":1,"two":2,"three":3,"four":4,"five":5}
    clean_data=[]
    unique_data=set()
    
    for user in data:
        raw_rating = str(user["rating"]).strip().lower()
        if (raw_rating in letter_to_rating):
            raw_rating=letter_to_rating[raw_rating]
        user["rating"]=raw_rating
        #Handle mising values
        raw_age=user.get("age")
        if (raw_age==None):
            user["age"]=None
        #deduplication
        if (user["name"].strip() in unique_data):
            continue
        unique_data.add(user["name"])
        clean_data.append(user)
    return clean_data
            
            
        
        
            

In [137]:
data=clean_data(data)

In [138]:
#Get meanigful insight from data
def get_insights(data):
    total_rating=0
    for user in data:
        total_rating += float(user["rating"])
    print(f"avg rating ={total_rating/len(data)}")

#percentage of user with poor rating
    poor_rating=0
    for user in data:
        if (float(user["rating"]) < 3):
            poor_rating += 1
    print(f"% of user  with poor rating = {poor_rating/len(data)*100}%")
            

In [139]:
get_insights(data)

avg rating =3.9
% of user  with poor rating = 20.0%


In [140]:
def get_recommendations(data):
    recommendations=[]

    for user in data:
        curr_recommendation={}
        curr_recommendation["name"]=user["name"]
        if(float(user["rating"]) >=4 ):
            curr_recommendation['brand']="apple"
        else:
            curr_recommendation['brand']="sumsung"
        recommendations.append(curr_recommendation)
    return recommendations

In [141]:
get_recommendations(data)

[{'name': 'Alice', 'brand': 'apple'},
 {'name': 'Bob', 'brand': 'apple'},
 {'name': 'charlie', 'brand': 'sumsung'},
 {'name': 'Diana', 'brand': 'apple'},
 {'name': 'Eve', 'brand': 'sumsung'}]

In [2]:
import numpy as np
import time

In [150]:
np_list=np.array([1,2,3,4,5])
start_time =time.time()
squre_list=np_list+2
end_time = time.time()
print(f"performing time is {end_time-start_time}",squre_list)

performing time is 0.0037021636962890625 [3 4 5 6 7]


In [154]:
td_array=np.array([[1,2,3,4],[5,6,7,8],[9,1,3,5]])
print(td_array,td_array.shape,td_array.dtype,type(td_array))

[[1 2 3 4]
 [5 6 7 8]
 [9 1 3 5]] (3, 4) int32 <class 'numpy.ndarray'>


In [16]:
np_arr=np.array([[1,2,3,4],[5,6,7,8]])
# np_arr=np_arr.reshape((4,2))
# flattern=np_arr.flatten()

print(flattern,flattern.shape)

[1 2 3 4 5 6 7 8] (8,)


In [17]:
#indexing dimension array
np_arr=np.array([[1,2,3,4],[5,6,7,8]])
print(np_arr[0][2])

3


In [20]:
#fancy indexing
np_arr=np.array([1,2,3,4,5,6,7,8])
idx=[0,1,3]
print(np_arr[idx])

[1 2 4]


In [24]:
#boolean indexing
np_arr=np.array([1,2,3,4,5,6,7,8])

print(np_arr[np_arr>3])
print(np_arr[np_arr<3])
print(np_arr[np_arr%2==0])
print(np_arr[np_arr%2!=0])


[4 5 6 7 8]
[1 2]
[2 4 6 8]
[1 3 5 7]


In [29]:
#slicing
np_arr=np.array([1,2,3,4,5,6,7,8])
print(np_arr[1:4])
print(np_arr[1:])
print(np_arr[:4])
print(np_arr[::2],np_arr.dtype)

[2 3 4]
[2 3 4 5 6 7 8]
[1 2 3 4]
[1 3 5 7] int32


In [36]:
#multi-dimension arrays

arr2D=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(np.sum(arr2D))

sum_of_colums=np.sum(arr2D, axis=0)
print(sum_of_colums)

sum_of_rows=np.sum(arr2D,axis=1)
print(sum_of_rows)

print(arr2D[0:2,1:2])



45
[12 15 18]
[ 6 15 24]
[[2]
 [5]]


In [43]:
#3D array

arr3D=np.array([[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]]])  #2 x 3 x 2
print(arr3D,arr3D.shape)

print(arr3D[1,1,0])


print(arr3D[:, 0, :])
print(arr3D[:, :, 0])

arr3D[:, 0, :]=99
print(arr3D)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] (2, 3, 2)
9
[[1 2]
 [7 8]]
[[ 1  3  5]
 [ 7  9 11]]
[[[99 99]
  [ 3  4]
  [ 5  6]]

 [[99 99]
  [ 9 10]
  [11 12]]]


In [49]:
#normalize
arr=np.array([[1,2],[3,4]])
mean=np.mean(arr)
print(mean)

std_dev = np.std(arr)

normalized_arr =(arr-mean)/std_dev
print(normalized_arr)

print(std_dev)
print(np.sqrt(5/4))

2.5
[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]
1.118033988749895
1.118033988749895
